/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frm;
import frm.VariableX;
import frm.VariableY;
import imc.*;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Esaú
 */
public class main extends javax.swing.JFrame {
 DefaultTableModel modelo;
      calculo calc; 
      DecimalFormat format;
      public double resA ;
         VariableY formY;
        VariableX formX;
    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        
        formY=new VariableY(); 
        formX=new VariableX();
          calc = new calculo();
         this.modelo = (DefaultTableModel) this.jTable1.getModel();
        calc.xp = new ArrayList<Double>();
       calc.y = new ArrayList<Double>();
        calc.xC = new ArrayList<Double>();
       calc.yC = new ArrayList<Double>();
        calc.xy = new ArrayList<Double>();
        this.BtnX.setEnabled(false);
      this.BtnY.setEnabled(false);
   
     format = new DecimalFormat("#########.###");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ynum = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        xnum = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        sumaP = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        sumaA = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        sumaXC = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        sumaYC = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        sumaXY = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        sxx = new javax.swing.JTextField();
        sxy = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Syy = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        mediaY = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        mediaX = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        BtnX = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        BtnY = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 255));
        jLabel3.setText("Aplicación Estadística Regresión y Correlación");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 740, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Agregar Datos");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Altura (X)");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));

        ynum.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(ynum, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 150, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Peso (Y)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        xnum.setBackground(new java.awt.Color(204, 255, 255));
        xnum.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(xnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 130, 30));

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 100, 30));

        jButton3.setBackground(new java.awt.Color(204, 255, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Limpiar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, 90, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Realizar Cálculos");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, -1, -1));

        jButton2.setBackground(new java.awt.Color(204, 255, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Calcular");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 120, 90, 30));

        jButton7.setBackground(new java.awt.Color(204, 255, 204));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setText("Grafica");
        jButton7.setPreferredSize(new java.awt.Dimension(70, 25));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 160, 90, 30));

        jTable1.setBackground(new java.awt.Color(204, 255, 204));
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Altura(X)", "Peso(Y)", "X²i", "Y²i", "Xi.Yi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 740, 90));

        sumaP.setEditable(false);
        sumaP.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(sumaP, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 140, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("∑x");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 40, -1));

        sumaA.setEditable(false);
        sumaA.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(sumaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 140, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("∑y");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 40, -1));

        sumaXC.setEditable(false);
        sumaXC.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(sumaXC, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 130, 30));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("∑x²");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 40, -1));

        sumaYC.setEditable(false);
        sumaYC.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(sumaYC, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, 130, 30));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setText("∑y²");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, 40, -1));

        sumaXY.setEditable(false);
        sumaXY.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(sumaXY, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 320, 140, 30));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel12.setText("∑xy");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 300, 50, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Cálculos");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, -1, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel14.setText("Sxx");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, -1, -1));

        sxx.setEditable(false);
        sxx.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(sxx, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 80, 30));

        sxy.setEditable(false);
        sxy.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(sxy, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 80, 30));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setText("Sxy");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, -1, -1));

        Syy.setEditable(false);
        Syy.setBackground(new java.awt.Color(204, 255, 255));
        Syy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SyyActionPerformed(evt);
            }
        });
        getContentPane().add(Syy, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 90, 30));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel15.setText("Syy");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, -1, -1));

        mediaY.setEditable(false);
        mediaY.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(mediaY, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 430, 80, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Ȳ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 400, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Cálculos");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, -1, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel16.setText("x̄");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 400, 20, -1));

        mediaX.setEditable(false);
        mediaX.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(mediaX, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 430, 90, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Calcular variable independiente X");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, -1, -1));

        BtnX.setBackground(new java.awt.Color(204, 255, 204));
        BtnX.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnX.setText("Calcular X");
        BtnX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnXActionPerformed(evt);
            }
        });
        getContentPane().add(BtnX, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, 130, 40));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Calcular variable independiente Y");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 500, -1, -1));

        BtnY.setBackground(new java.awt.Color(204, 255, 204));
        BtnY.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnY.setText("Calcular Y");
        BtnY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnYActionPerformed(evt);
            }
        });
        getContentPane().add(BtnY, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 490, 120, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1050, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        double xyT = 0;
        double xCT = 0;
        double yCT = 0;

        if (this.xnum.getText().isEmpty() || this.ynum.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese valores en ambos campos", "Error",JOptionPane.ERROR_MESSAGE);
        }else{

            if (Double.parseDouble(this.xnum.getText())<0 || Double.parseDouble(this.ynum.getText())<0) {
                JOptionPane.showMessageDialog(null, "Por favor ingrese valores positivos en ambos campos", "Error",JOptionPane.ERROR_MESSAGE);
            }else{
                this.modelo.getDataVector().removeAllElements();
                calc.xp.add(Double.parseDouble(this.xnum.getText()));
                //x.add(Double.parseDouble(this.xnum.getText()));
                calc.y.add(Double.parseDouble(this.ynum.getText()));

                xyT = Double.parseDouble(this.xnum.getText())*Double.parseDouble(this.ynum.getText());
                xCT = Math.pow(Double.parseDouble(this.xnum.getText()),2);
                yCT = Math.pow(Double.parseDouble(this.ynum.getText()),2);
                calc.xy.add(xyT);
                calc.xC.add(xCT);
                calc.yC.add(yCT);

                for (int i = 0; i < calc.xp.size(); i++) {

                    String[] datos = { Double.toString(calc.xp.get(i)),
                        Double.toString(calc.y.get(i)),Double.toString(calc.xC.get(i)),
                        Double.toString(calc.yC.get(i)),Double.toString(calc.xy.get(i))};
                    this.modelo.addRow(datos);
                }
            }
        }

        this.limpiar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SyyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SyyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SyyActionPerformed

    private void BtnXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnXActionPerformed
        // TODO add your handling code here:
        formX.resAX(calc.AX());
        formX.resBX(calc.BX());
        formX.resRX(calc.RX());
        formX.setVisible(true);
    }//GEN-LAST:event_BtnXActionPerformed

    private void BtnYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnYActionPerformed
        // TODO add your handling code here:
           formY.resA(calc.A());
        formY.resB(calc.B());
       formY.resR(calc.RY());
      formY.setVisible(true);
    }//GEN-LAST:event_BtnYActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:

        String formula = "";

        //        double acumuladorY = 0;
        //        double acumuladorXC = 0;
        //        double acumuladorYC = 0;
        //        double acumuladorXY = 0;
        //        for (int i = 0; i < x.size(); i++) {
            //
            //        acumuladorY += y.get(i);
            //        acumuladorXC += xC.get(i);
            //        acumuladorYC += yC.get(i);
            //        acumuladorXY += xy.get(i);
            //
            //        }
        this.sumaP.setText(format.format(calc.sumaX()));
        this.sumaA.setText(format.format(calc.sumaY()));
        this.sumaXC.setText(format.format(calc.sumaXC()));
        this.sumaYC.setText(format.format(calc.sumaYC()));
        this.sumaXY.setText(format.format(calc.sumaXY()));

        //        calc.setSumay(acumuladorY);
        //        calc.setSumayC(acumuladorYC);
        //        calc.setSumaxy(acumuladorXY);
        //        calc.setTamanio(x.size());

        this.sxx.setText(format.format(calc.SXX()));
        this.sxy.setText(format.format(calc.SXY()));
        this.mediaX.setText(format.format(calc.mediaX()));
        this.mediaY.setText(format.format(calc.mediaY()));
        this.Syy.setText(format.format(calc.SYY()));
        this.BtnX.setEnabled(true);
        this.BtnY.setEnabled(true);
        //System.out.println(this.A());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
          calc.grafic();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.cleanBtn();
    }//GEN-LAST:event_jButton3ActionPerformed
    private void limpiar(){
    this.xnum.setText("");
    this.ynum.setText("");
    }
    private void cleanBtn(){
       this.limpTable();
         this.sumaP.setText(null);
        this.sumaA.setText(null);
        this.sumaXC.setText(null);
        this.sumaYC.setText(null);
        this.sumaXY.setText(null);
        this.Syy.setText(null);
        this.sxx.setText(null);
        this.sxy.setText(null);
        this.mediaX.setText(null);
        this.mediaY.setText(null);
  
    
    };
    private void limpTable(){
        for (int i = 0; i < this.jTable1.getRowCount(); i++) {
            modelo.removeRow(i);
            i-=1;
        }
       calc.xp.removeAll(calc.xp);
       calc.y.removeAll(calc.y);
       calc.yC.removeAll(calc.yC);
       calc.xC.removeAll(calc.xC);
       calc.xy.removeAll(calc.xy);
    };
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnX;
    private javax.swing.JButton BtnY;
    private javax.swing.JTextField Syy;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField mediaX;
    private javax.swing.JTextField mediaY;
    private javax.swing.JTextField sumaA;
    private javax.swing.JTextField sumaP;
    private javax.swing.JTextField sumaXC;
    private javax.swing.JTextField sumaXY;
    private javax.swing.JTextField sumaYC;
    private javax.swing.JTextField sxx;
    private javax.swing.JTextField sxy;
    private javax.swing.JFormattedTextField xnum;
    private javax.swing.JFormattedTextField ynum;
    // End of variables declaration//GEN-END:variables
}
