/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frm;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan
 */
public class VariableX extends javax.swing.JFrame {

    /**
     * Creates new form VariableX
     */
    private double respA;
    private double respB;
    private double R;
    DecimalFormat format;
    public VariableX() {
        initComponents();
        this.limpiar();
         this.formula.setEditable(false);
       this.A.setEditable(false);
       this.B.setEditable(false);
       this.resp.setEditable(false);
         format = new DecimalFormat("#########.###");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        A = new javax.swing.JTextField();
        B = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        formula = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        peso = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        resp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lPes = new javax.swing.JLabel();
        r1 = new javax.swing.JTextField();
        r = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        jLabel1.setText("A");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        A.setEditable(false);
        A.setBackground(new java.awt.Color(255, 204, 204));
        A.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(A, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 100, 40));

        B.setEditable(false);
        B.setBackground(new java.awt.Color(255, 204, 204));
        B.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(B, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 100, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Fórmula");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        formula.setEditable(false);
        formula.setBackground(new java.awt.Color(255, 204, 204));
        formula.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(formula, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 300, 30));

        jButton1.setBackground(new java.awt.Color(153, 255, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 90, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Ingrese el peso (KLg)");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        peso.setBackground(new java.awt.Color(255, 204, 204));
        peso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesoActionPerformed(evt);
            }
        });
        peso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pesoKeyTyped(evt);
            }
        });
        getContentPane().add(peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 160, 30));

        jLabel2.setText("B");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 30, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("X=");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("La Altura esperada es:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));

        resp.setEditable(false);
        resp.setBackground(new java.awt.Color(255, 204, 204));
        resp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(resp, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 320, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("r=");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("r²=");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, -1, -1));
        getContentPane().add(lPes, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 210, 40));

        r1.setEditable(false);
        r1.setBackground(new java.awt.Color(255, 204, 204));
        r1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 100, 30));

        r.setEditable(false);
        r.setBackground(new java.awt.Color(255, 204, 204));
        r.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(r, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 100, 30));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 0));
        jLabel11.setText("Cálculo de la Altura Esperada");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Coeficiente de Correlación");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img3.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
        String formula = "";
        this.B.setText(format.format(this.respB));
      this.A.setText(format.format(this.respA));
        formula = "X = "+format.format(respB)+" + ("+format.format(this.respA)+")(Y)";
        
      this.formula.setText(formula);
    }//GEN-LAST:event_formMouseMoved

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String resPeso;
        if (this.peso.getText().length()>0) {
            if (Double.parseDouble(this.peso.getText())<0) {
                JOptionPane.showMessageDialog(null, "Por favor ingrese un valor positivo", "Error",JOptionPane.ERROR_MESSAGE);
            }else{

                resPeso = format.format(respA+(respB*Double.parseDouble(this.peso.getText())));
                this.resp.setText(resPeso);
                this.r.setText(format.format(this.R));
                this.r1.setText(format.format(Math.pow(R, 2)));
                this.lPes.setText(resPeso);

            }
        }else{
            JOptionPane.showMessageDialog(null, "Por favor ingrese un valor válido", "Error",JOptionPane.ERROR_MESSAGE);

        }
        this.peso.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (Character.isLetter(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_pesoKeyTyped

    private void pesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        this.limpiar();
    }//GEN-LAST:event_formWindowActivated
 public void resAX(double a){
        this.respA = a;
    };
    public void resBX(double b){
        this.respB = b;
    };
    public void resRX(double R){
        this.R = R;
    };
    
     public void limpiar(){
        this.A.setText(null);
        this.B.setText(null);
        this.peso.setText(null);
        this.formula.setText(null);
        this.resp.setText(null);
        this.r.setText(null);
        this.r1.setText(null);
    };
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VariableX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VariableX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VariableX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VariableX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VariableX().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField A;
    private javax.swing.JTextField B;
    private javax.swing.JTextField formula;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lPes;
    private javax.swing.JFormattedTextField peso;
    private javax.swing.JTextField r;
    private javax.swing.JTextField r1;
    private javax.swing.JTextField resp;
    // End of variables declaration//GEN-END:variables
}
